Sprint 3
s-ratashnyuk/middle.messenger.praktikum.yandex pull request #3
Opened 2022-04-29 12:13 UTC by s-ratashnyuk

2022-04-30 06:37 UTC, agadoev requested changes
Привет) 

Спасибо за работу, мне понравился твой подход к написаю кода. Однако я не увидел тестов, и их точно нужно будет прикрутить. Поверь, в реальной разработке они ооочень сильно пригодятся)
Так же отметил пару моментов, на которые стоит обратить внимание.

Дописывай тесты, поправь, что я отметил, и двинемся дальше :)

2022-04-30 06:37 UTC, agadoev commented on src/components/Core/Block/Block.ts
> +// выключаю, тк это обертка, а не отдельный класс
На самом деле не важно, обертка это или отдельный класс, все равно лучше придерживаться правила "один файл - один класс". Представь, что ты работаешь над какой-то фичей и тебе вдруг понадобилась эта обертка. 
Какой вариант очевиднее - если она лежит в файле withBlockAsPage.ts или в файле Block.ts?

2022-04-30 06:37 UTC, agadoev commented on src/pages/login/login.ts
> +      LoginController.doLogin(res.values.inputLogin, res.values.inputPassword);
Что будет, если при вызове API, в ответе придет 500 ошибка? Я к тому, что  неплохо было бы сделать обработку ошибок от сервера, поместив вызов API в блок try {...} catch {...}

UPD. Увидел у тебя обработку ошибок в методе .catch(), посылается событие на шину, но не могу найти подписки на это событие и какую-то обработку. Если она есть - неправь меня, если нет - неплохо бы прикрутить. Можно вывести пользователю сообщение об ошибке в нотификации сверху в углу

2022-04-30 06:37 UTC, agadoev commented on src/controllers/loginController.ts
> +    (async () => {
действительно ли тут нужо использовать IIFE? Или это только усложняет код?

2022-04-30 06:37 UTC, agadoev commented on src/models/userModel.ts
> +  login(login: string, password: string) {
Будет куда понятнее, если вся логика, касающаяся запросов к API, будет содержаться в контроллерах, а не в моделях. Меня это сначала ввело в заблуждение. Обычно на всех проектах, на которых я работал (и ты скоре всего будешь работать), за запросы отвечают именно контроллеры. Модели описывают данные и иногда могут содержать в себе логику запросов к бд (если мы про backend говорит), но запросы в моделях я еще не встречал

2022-04-30 13:17 UTC, s-ratashnyuk commented on src/models/userModel.ts
> +  login(login: string, password: string) {
Перенес логику запросов в контроллеры. Оставил только в модели пользователя общие методы, чтобы не дублировать код и не вносить нелогичность (например, на мой взгляд не логично, что получать информацию о пользователе надо было бы в контроллере loginController)

2022-04-30 13:17 UTC, s-ratashnyuk commented on src/controllers/loginController.ts
> +    (async () => {
Да, я что-то перемудрил и сам себя запутал. Достаточно просто объявить async метод класса. Переделал

2022-04-30 13:19 UTC, s-ratashnyuk commented on src/pages/login/login.ts
> +      LoginController.doLogin(res.values.inputLogin, res.values.inputPassword);
Вызывается метод handleLoginFail, в нем - показываю пользователю поп ап, в котором рассказываю об ошибке.
https://github.com/s-ratashnyuk/middle.messenger.praktikum.yandex/pull/3/files/76ebc0689bc22df1891e7ea5b682578e82a11568#diff-479d9284e5568b9085f92cd2abd4b02dd3b95a97ebf234febda8444403f84534R59

2022-04-30 13:20 UTC, s-ratashnyuk commented on src/components/Core/Block/Block.ts
> +// выключаю, тк это обертка, а не отдельный класс
Переделал

2022-04-30 13:22 UTC, s-ratashnyuk commented
> Привет)
> 
> Спасибо за работу, мне понравился твой подход к написаю кода. Однако я не увидел тестов, и их точно нужно будет прикрутить. Поверь, в реальной разработке они ооочень сильно пригодятся) Так же отметил пару моментов, на которые стоит обратить внимание.
> 
> Дописывай тесты, поправь, что я отметил, и двинемся дальше :)

Нам на установочной встрече 3го спринта говорили, что тесты можно в этом спринте не писать. Я прикрутил jest и написал пару тестов на утилиты, этого на сейчас достаточно? :-) Так-то согласен, без тестов сложнее. Даже сейчас, пока правил код, один раз тесты сработали.

2022-05-02 17:00 UTC, agadoev commented
Привет
Спасибо за правки, все вроде ок)
Работу принимаю, удачи в дальнейшем :)

2022-05-02 17:57 UTC, merged